version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/server
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 2400
      runas: ubuntu