version: '3.7'

services:
  nginx_proxy:
    image: nginx:latest
    restart: "on-failure"
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./client/build:/usr/share/nginx/html
    container_name: nginx_proxy
    networks:
      - default
    depends_on:
      - server

  server:
    image: recjoon-server:latest
    build:
      context: ./server/
      dockerfile: dockerfile
    restart: "on-failure"
    environment:
      - RECJOON_RDS_HOST
      - RECJOON_RDS_PORT
      - RECJOON_RDS_USERNAME
      - RECJOON_RDS_PASSWORD
      - RECJOON_RDS_DATABASE
      - RECJOON_SERVER_HOST
      - RECJOON_SERVER_PORT
    networks:
      - default
    container_name: server
    expose: 
      - "8080"
    volumes:
      - './server:/app'
      - '/app/node_modules'
    stdin_open: true
    tty: true

networks:
  default: