version: '3.7'

services:
  nginx_proxy:
    image: nginx:latest
    restart: always
    build:
      context: ./
      dockerfile: dockerfile.nginx
    container_name: nginx_proxy
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./client/build:/usr/share/nginx/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    

