version: '3.7'

services:
  server-green:
    image: recjoon-server:latest
    build:
      context: ./server/
      dockerfile: dockerfile
    restart: "on-failure"
    environment:
      - RECJOON_RDS_HOST
      - RECJOON_RDS_PORT
      - RECJOON_RDS_USERNAME
      - RECJOON_RDS_PASSWORD
      - RECJOON_RDS_DATABASE
      - RECJOON_SERVER_HOST
      - RECJOON_SERVER_PORT
      - RECJOON_RDS_MASTER_HOST
    ports: 
      - 8081:8080
    volumes:
      - './server:/app'
      - '/app/node_modules'
    stdin_open: true